version: '3'

services:
  db:
    container_name: postgres-db
    image: postgres:15.1
    volumes:
      - volumedbSQL:/var/lib/postgresql/data1
    environment:
      - POSTGRES_PASSWORD=mypassword

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456 
      - PGADMIN_DEFAULT_EMAIL=superman@google.com

      
volumes:
  volumedbSQL:
    external: true